# Generated by Django 5.0.3 on 2024-04-08 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Billing_Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(default='', max_length=100)),
                ('Email', models.CharField(default='', max_length=100)),
                ('Address', models.CharField(default='', max_length=100)),
                ('City', models.CharField(default='', max_length=100)),
                ('State', models.CharField(default='', max_length=100)),
                ('Zip', models.IntegerField(default='', max_length=50)),
            ],
        ),
    ]
