# Generated by Django 5.0.3 on 2024-04-08 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Demo_D', '0002_alter_billing_address_zip'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billing_address',
            name='City',
        ),
    ]
