# Generated by Django 5.0.3 on 2024-04-09 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HarvestHub', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=150)),
                ('name', models.CharField(max_length=150)),
                ('quantity', models.FloatField()),
                ('total_amount', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='farmer',
            name='date_of_birth',
        ),
    ]
