# Generated by Django 5.0.3 on 2024-04-10 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HarvestHub', '0003_sales_remove_farmer_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmer',
            name='gender',
            field=models.CharField(max_length=1),
        ),
    ]
