# Generated by Django 5.0.3 on 2024-04-10 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HarvestHub', '0004_alter_farmer_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmer',
            name='phone_number',
            field=models.CharField(max_length=15),
        ),
    ]
