# Generated by Django 5.0.3 on 2024-04-10 11:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HarvestHub', '0005_alter_farmer_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesProductPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('price', models.FloatField()),
                ('created_at', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
    ]
