# Generated by Django 5.0.3 on 2024-04-10 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HarvestHub', '0006_salesproductprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='status',
            field=models.CharField(default='Process', max_length=20),
        ),
    ]
